### ISSUE TITLE
Setup Repeat TTS

### ISSUE THREAD

**Issue by Xedhryx** [mjfwebb/twitch-bot#142]
I was thinking of setting up something like the streamer Charborg has in a lot of his content, where it uses a TTS voice, and connects to the channel for repeating messages. I'm wondering how easy it can be created, and I'm learning to do stuff like this myself too, is there any chance this can be worked on, or given help to understand how to set this up?

Here is something that's very similar to what I'm asking of [Charborg](https://www.youtube.com/watch?v=JHHQ_dG-Bl8)

Instead of showing "x out of 10" I'd just want a certain amount of repeated messages to trigger the TTS, not combo/messages in a row, but repeated messages in a certain time frame.

**Comment by mjfwebb** [comment]
Hey @Xedhryx! This looks like a really fun feature. That video was great :laughing:

I guess there's some kind of criteria a message has to match? For example, possibly:

- it can't be over x (10?) words
- can't have emotes?
- must be repeated 10 times within a certain timeframe

Sounds like a fun thing to add, and not too difficult. Once we nail down the particulars I'll probably add this :+1:

**Comment by Xedhryx** [comment]
I'd say we could set a constraint to let people choose the times people need to say the same thing for it to trigger?
Having less than x words would probably be helpful so the TTS doesnt go on for a long time though lol
If we could add emotes, we could show it on screen like Charborg too
