### ISSUE TITLE
Add !songrequest command

### ISSUE THREAD

**Issue by mjfwebb** [mjfwebb/twitch-bot#20]
add a song request with channel points, it will submit it to a queue Spotify will play

_Originally posted by @JumpyLionnn in https://github.com/mjfwebb/twitch-bot/issues/15#issuecomment-1378483726_

**Comment by JumpyLionnn** [comment]
you should probably add a moderation list, so moderators can check those songs wont get you banned

**Comment by mjfwebb** [comment]
Implemented as !queuesong or !qs

Currently set to require mod or above privileges.
